### ISSUE TITLE
Reference to the algorithm

### ISSUE THREAD

**Issue by 461353349** [rohan-sawhney/conformal-parameterization#1]
Can you supply the reference to the LSCM, SCP, Circle Patterns, CETM. That will help us to understand the code.

**Comment by rohan-sawhney** [comment]
Here are the links to the papers:
1) LSCM: https://members.loria.fr/Bruno.Levy/papers/LSCM_SIGGRAPH_2002.pdf
2) SCP: http://www.geometry.caltech.edu/pubs/MTAD08.pdf
3) CP: http://www.cs.jhu.edu/~misha/Fall09/Kharevych06.pdf
4) CETM: http://multires.caltech.edu/pubs/ConfEquiv.pdf

I suggest taking a look at this library as well: https://geometrycollective.github.io/boundary-first-flattening/
It implements an algorithm thats faster than the ones above, and has several features to edit uv maps.

**Comment by 461353349** [comment]
It is very nice of you!
